import { Text } from '@asyncapi/generator-react-sdk';

export default function CodegenComment() {
  return (
    <Text newLines={1}>
      {`/**
 * Generated by the AsyncAPI Generator. DO NOT EDIT!
 */`}
    </Text>
  );
}
